import type { Metadata } from "next";

import { Khand } from "next/font/google";
import "../globals.css";
import Header from "@components/layout/Header/Header";
import Footer from "@components/layout/Footer/Footer";

const khand = Khand({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Kaz Local Studio ",
  description: "Generated by the Colorful Team!",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={khand.className}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
